-- Blok M MSME discovery — initial schema
-- PostGIS is optional. Bounding-box queries use lat/lng columns for the MVP.
-- UUIDs are generated by the API/seed (no pgcrypto required).

CREATE TABLE IF NOT EXISTS places (
  id UUID PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('japanese', 'street', 'cafe', 'retail', 'other')),
  vibes TEXT[] NOT NULL DEFAULT '{}',
  price TEXT NOT NULL CHECK (price IN ('$', '$$', '$$$')),
  open_late BOOLEAN NOT NULL DEFAULT FALSE,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  neighborhood TEXT NOT NULL,
  address TEXT NOT NULL,
  hours TEXT,
  description TEXT NOT NULL,
  source_note TEXT NOT NULL DEFAULT 'Hand-curated seed. Hours and pins are approximate; confirm on-site.',
  aliases TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS places_geo_idx ON places (lat, lng);
CREATE INDEX IF NOT EXISTS places_category_idx ON places (category);
CREATE INDEX IF NOT EXISTS places_open_late_idx ON places (open_late);
CREATE INDEX IF NOT EXISTS places_price_idx ON places (price);

CREATE TABLE IF NOT EXISTS suggestions (
  id UUID PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('new_place', 'correction')),
  place_id UUID REFERENCES places(id) ON DELETE SET NULL,
  name TEXT,
  category TEXT,
  notes TEXT NOT NULL,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS suggestions_status_idx ON suggestions (status, created_at DESC);
